# Generated by Django 5.1.7 on 2025-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('received_date', models.DateField()),
                ('order_type', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
            ],
        ),
    ]
